#!/bin/bash

CMAKE_FLAGS='-DCMAKE_BUILD_TYPE=DEBUG -DCMAKE_INSTALL_PREFIX=. -DBUILD_SHARED_LIBS=ON -DBUILD_PROGRAMS=OFF -DBUILD_EXAMPLES=OFF -DBUILD_TESTING=OFF -DENABLE_EXTERNAL_LIBS=ON -DENABLE_MPEG=ON -DENABLE_CPU_CLIP=OFF -DENABLE_BOW_DOCS=OFF -DENABLE_EXPERIMENTAL=OFF -DENABLE_CPACK=OFF -DINSTALL_MANPAGES=OFF -DENABLE_COMPATIBLE_LIBSNDFILE_NAME=ON -DENABLE_SSE2=ON'

git submodule update build/submodules/libsndfile
mkdir build/submodules/libsndfile/CMakeBuild
cd build/submodules/libsndfile/CMakeBuild
cmake .. $CMAKE_FLAGS
make && make install

